version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      symfony:
        patterns:
          - "symfony/*"
      dev-tools:
        patterns:
          - "phpunit/*"
          - "phpstan/*"
          - "friendsofphp/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
