<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->scalarNode('root_view')
                ->defaultValue('base.html.twig')
                ->cannotBeEmpty()
                ->info('The root Twig template used to render the full HTML page on first visit.')
            ->end()
            ->scalarNode('version')
                ->defaultNull()
                ->info('Asset version string. When it changes, Inertia triggers a full page reload. Set to null to disable.')
            ->end()
            ->booleanNode('intercept_validation_errors')
                ->defaultTrue()
                ->info('When true, ValidationFailedException (MapRequestPayload/MapQueryString or manual throw) on Inertia requests is converted into the error flow: errors in session + 303 redirect back. Set to false to keep Symfony\'s default 422 behavior.')
            ->end()
            ->booleanNode('encrypt_history')
                ->defaultFalse()
                ->info('Globally enable browser history encryption for all Inertia responses. Can be overridden per-render via Inertia::encryptHistory().')
            ->end()
            ->booleanNode('expose_shared_prop_keys')
                ->defaultTrue()
                ->info('When true, the page object includes a sharedProps field listing keys coming from Inertia::share(). Allows the client to distinguish shared from page-specific props.')
            ->end()
            ->booleanNode('ssr_enabled')
                ->defaultFalse()
                ->info('Enable Server-Side Rendering via an external Node.js SSR server.')
            ->end()
            ->scalarNode('ssr_url')
                ->defaultValue('http://127.0.0.1:13714')
                ->cannotBeEmpty()
                ->info('URL of the SSR server (used only when ssr_enabled is true).')
            ->end()
            ->scalarNode('ssr_bundle')
                ->defaultNull()
                ->info('Path to the SSR bundle JS file. If null, auto-detected from common paths (bootstrap/ssr/ssr.mjs, public/build/ssr/ssr.mjs).')
            ->end()
            ->booleanNode('ssr_throw_on_error')
                ->defaultFalse()
                ->info('When true, SSR rendering failures throw a SsrException instead of silently falling back to client-side rendering. Useful for E2E tests.')
            ->end()
            ->arrayNode('pages')
                ->addDefaultsIfNotSet()
                ->info('Component file validation settings.')
                ->children()
                    ->booleanNode('ensure_pages_exist')
                        ->defaultFalse()
                        ->info('When true, Inertia::render() will throw if the component file does not exist on disk. Requires pages.paths to be configured.')
                    ->end()
                    ->arrayNode('paths')
                        ->scalarPrototype()->cannotBeEmpty()->end()
                        ->defaultValue([])
                        ->info('Directories to scan for component files (e.g. "%kernel.project_dir%/assets/js/pages").')
                    ->end()
                    ->arrayNode('extensions')
                        ->scalarPrototype()->end()
                        ->defaultValue(['vue', 'jsx', 'tsx', 'js', 'ts', 'svelte'])
                        ->info('File extensions to consider when scanning for component files.')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('testing')
                ->addDefaultsIfNotSet()
                ->info('Settings for test assertions (AssertableInertiaPage).')
                ->children()
                    ->booleanNode('ensure_pages_exist')
                        ->defaultTrue()
                        ->info('When true, AssertableInertiaPage::component() validates the file exists on disk. Uses pages.paths and pages.extensions.')
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
