name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, intl
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPCS
        run: vendor/bin/phpcs src/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src/

  tests:
    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} - ${{ matrix.stability }}
    runs-on: ubuntu-24.04
    needs: code-quality

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        symfony: ['6.4', '7.0', '7.1']
        stability: [prefer-lowest, prefer-stable]
        exclude:
          # Symfony 7.x requires PHP 8.2+
          - php: '8.1'
            symfony: '7.0'
          - php: '8.1'
            symfony: '7.1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, intl
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-composer-
            ${{ runner.os }}-composer-

      - name: Set Symfony version
        run: |
          composer require "symfony/framework-bundle:^${{ matrix.symfony }}" --no-interaction --no-update
          composer require "symfony/http-kernel:^${{ matrix.symfony }}" --no-interaction --no-update
          composer require "symfony/dependency-injection:^${{ matrix.symfony }}" --no-interaction --no-update
          composer require "symfony/config:^${{ matrix.symfony }}" --no-interaction --no-update
          composer require "twig/twig:^3.0" --no-interaction --no-update

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests with coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.php == '8.3' && matrix.symfony == '6.4' && matrix.stability == 'prefer-stable'
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
